### ISSUE TITLE
problem with authentication

### ISSUE THREAD

**Issue by tiagomendesdantas** [pablobarbera/instaR#10]
Hello Pablo!

Can you check if the authentication is working correctly? It seems that they have changed something related to it and that is affecting the package.

Thanks!

**Comment by pablobarbera** [comment]
Hey @tiagomendesdantas,

I just checked, and it works for me! What version of httr are you using? I know there were some issues with that, but it should work with the latest version. What error are you getting?

Thanks for reporting this!

Pablo

**Comment by tiagomendesdantas** [comment]
I'm sorry Pablo! Apparently I was setting the wrong redirect URIs. Everything is ok now! Thanks a lot!

**Comment by pablobarbera** [comment]
Great!
