### ISSUE TITLE
Error in callAPI(url, token)

### ISSUE THREAD

**Issue by ldlpdx** [pablobarbera/instaR#11]
I'm getting the above error when using the following code, which I took directly from your example.

``` r
pm <- getUserMedia("portlandmeadows", token, n=100, folder="pm_pics")
```

All of my authorizations have been included and verified through Instagram.

**Comment by mobcdi** [comment]
Hi Idlathrop,

If you give me a hand getting the code installed in R I can see if I get the same problems as you.
I have devtools installed but I think my install_github command is wrong
install_github("pablobarbera/instaR","/instaR" ) Any pointers?

**Comment by pablobarbera** [comment]
@mobcdi devtools::install_github("pablobarbera/instaR/instaR") should work. 
@ldlathrop I just tried the code above and it works for me! What's your sessionInfo()? Weird.

**Comment by federica2212** [comment]
Hi Pablo!
I type this code:

> tsq <- searchInstagram( lat=40.7577, lng=-73.9857, distance=500,token=token, n=500, folder=NULL,mindate="2014-12-31", maxdate="2014-01-01")

and I have:

> Error in callAPI(url, token) : Error!

Have you detected and solved this problem? 
Thanks!

**Comment by pablobarbera** [comment]
@federica2212 The problem is that you choose a `mindate` that is greater than `maxdate`. I have changed the function so that it now returns an error message when this happens. But just switching the values of `mindate` and `maxdate` should work. Thanks!

**Comment by FerDoranNie** [comment]
Hi Pablo. I have the next problem:
I type this: 
vocho <- searchInstagram(tag="volkswagenmexico", token=mytoken)
and I have
**Error in instaR::getUser(username = "volkswagenmexico", token = my_oauth) : 
  Error. User name not found.**
I check the code with debug and the problem is callAPI. I appreciate so much your help.
Thanks

**Comment by gauravlotia** [comment]
Error in getUserMedia(username = "swamilmahajan", token = my_oauth) : 
  Error. User name not found.

Why am I getting this error?
