### ISSUE TITLE
Issue with searchInstagram function

### ISSUE THREAD

**Issue by lyons7** [pablobarbera/instaR#26]
Hi! When I run your example for getting media with a given hashtag: 

obama <- searchInstagram(tag="obama", token=my_oauth)

I get an error message saying: Error in searchInstagram(tag = "obama", token = my_oauth) : 
  0 posts found.

Many thanks for help with this issue :)

**Comment by lyons7** [comment]
Also should mention -- I've set my scope to 'public_content'. Not sure if that makes any difference, but based on another person's issue (with getting user information) do I need to do an extra step to get authorization? Thanks!

**Comment by bluebelly42107** [comment]
I am having the same issue. Either it returns an error with 0 posts, or it goes through the process of downloading pictures up to the number specified, and the directory folder has a smaller number of pictures than R says it downloads.

**Comment by lyons7** [comment]
Thank god! I thought I was crazy or just not doing something correctly.

Could it have something to do with Instagram's new Permissions? I tried to
submit a request for getting permissions but it got denied (not sure if
they have figured out giving permissions for academic research yet). Do you
think this is because we need more than the 'basic' set of permissions? Or
something else?
