### ISSUE TITLE
getUserMedia limited to 20 posts

### ISSUE THREAD

**Issue by padpadpadpad** [pablobarbera/instaR#30]
Hi

I am pretty new to this hence the opening and closing! I did not want to submit it when I did!

Basically the new [permissions](https://www.instagram.com/developer/review/) of Instagram mean you can only get the last 20 posts while in "Sandbox" mode before you make your app live.

Any idea how easy it is to submit your app for review or if there is another workaround.

My code and output as so:

``` R
CopperPics <- getUserMedia(username = "coppercar_thesausage", token = my_oauth, n = 48, folder = 'data')

20 posts
Downloading pictures...
```

Whereas there are actually 48 posts in that account...

**Comment by padpadpadpad** [comment]
Hi

I am pretty new to this hence the opening and closing! I did not want to submit it when I did!

Basically the new [permissions](https://www.instagram.com/developer/review/) of Instagram mean you can only get the last 20 posts while in "Sandbox" mode before you make your app live.

Any idea how easy it is to submit your app for review or if there is another workaround.

My code and output as so:

```{R}
CopperPics <- getUserMedia(username = "coppercar_thesausage", token = my_oauth, n = 48, folder = 'data')

20 posts
Downloading pictures...
```

Whereas there are actually 48 posts in that account...

**Comment by pablobarbera** [comment]
Yeah, unfortunately it does seem with the new version of the API only the 20 most recent posts are available... :( Nothing I can do on my end to fix this, sorry!
