### ISSUE TITLE
searchInstagram() failure

### ISSUE THREAD

**Issue by jamgreen** [pablobarbera/instaR#31]
I am attempting a test of the searchInstagram function after getting authentication from instagram

`rctid <- searchInstagram(tag = "rctid", token = my_oauth, n = 100)`

This is a tag for the Portland Timbers MLS team and I searched on their opening game day. I'm returning the following error:

Error in searchInstagram(tag = "rctid", token = my_oauth, n = 100) : 
  0 posts found.

Interestingly other functions did work like the getTagCount function returned 73693
`testtag <- getTagCount(tag="rctid", token = my_oauth)`

What am I doing wrong here?

**Comment by lyons7** [comment]
Instagram has changed their policies -- need to apply for permission to get access to their API beyond your own account :(
