### ISSUE TITLE
Error in get_oauth_sig() : OAuth has not been registered for this session

### ISSUE THREAD

**Issue by diegocgaona** [pablobarbera/instaR#33]
I'm trying to use the InstaR, but I'm having errors.
When I use the getUser(), I receive the error:

```
teste <- getUser(user = "diegogaona", token = insta_token)
Error in get_oauth_sig() : OAuth has not been registered for this session
```

When I try getFollowers()

```
teste <- getFollowers(username = "diegogaona", token = insta_token)
Error in getFollowers(username = "diegogaona", token = insta_token) : 
  Error. User name not found.
```

I follow the instructions to create the oauth(), the process is ok, (i'm in sandbox mode), but I don't understand why the errors occur.

```
<Token>
<oauth_endpoint>
 authorize: https://api.instagram.com/oauth/authorize
 access:    https://api.instagram.com/oauth/access_token
<oauth_app> instagram
  key:    XXXXXXXXXXXXXXXXXXXXXXXX
  secret: <hidden>
<credentials> access_token, user

---
```

Thes errors occur only for me?

**Comment by diegocgaona** [comment]
I had a error in my permissions, I fixed it. But I some features only works with my username, and others still receive errors.

A thing I noticed, In the first query, if I didn't use `username =` and `token =`, it works.
Example, this works:
`teste <- instaR::getUser("diegogaona", insta_token)`

But in `getFollowers()`, I have the error:

```
teste <- getFollowers(username = "diegogaona", token = insta_token)
0 followers
Error in getFollowers(username = "diegogaona", token = insta_token) : 
  Error. Zero followers?
```

But if I user other username, the message still `Error. User name not found.`
Some solution?

**Comment by diegocgaona** [comment]
Now I realize that the errors occur because the sandbox mode. I only get the followers, likes and others if they are in my sandbox too, and I can't access other profiles too.
The sandbox mode is very restrictive.
More info, here: http://stackoverflow.com/questions/33886881/instagram-api-returns-empty-data-for-sandbox-users-when-trying-to-access-liked-c

**Comment by sasijarvis** [comment]
same here

**Comment by nadeemkhan786** [comment]
"OAuth has not been registered for this session"  how to solve this error in  shiny application

**Comment by MVATFM** [comment]
Hi! Yo have to run this before the code  with your token:
api_key <- "-----"
api_secret <- "-------" 
access_token <- "----------" 
access_token_secret <- "-------------"  

setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)

**Comment by nadeemkhan786** [comment]
Yes
