### ISSUE TITLE
Error in instaOAuth

### ISSUE THREAD

**Issue by LucasPuente** [pablobarbera/instaR#34]
Hi,

I'm trying to get started using this package, but I keep getting the following error when trying to authenticate and authorize my app via the `instaOAuth` function:

`{"code": 400, "error_type": "OAuthException", "error_message": "Redirect URI does not match registered redirect URI"}`

Any ideas on how to address this?

Thanks!

**Comment by aymansir** [comment]
I'm having the same issue. Any fixes?

**Comment by j0bby** [comment]
I had the same issue,

I kind of solved this by : 

adding one more **`/`** at the end of the redirect _URL in your app settings in the sandbox `http://localhost:1410//`
Now when you use the `instaOAuth` function, you can log in.

When logged, you will be redirected to the URL : `localhost:1410//?code=...`

> Not Found

You have to remove one **`/`** from the URL :  `localhost:1410/?code=...` 

> Authentification complete. Please close this page and return to R.

There is still a mystery with this solution, cause you don't get the message from the fonction saying: "Authentification successful."

But i used the function geTagCount(), and it worked ;)

**Comment by aymansir** [comment]
Thanks so much @j0bby ! That helped alot.

**Comment by j0bby** [comment]
You can use `save(token, file="my_auth.R")` to save the token sent back from the function.
then you just have to call`load("my_auth.R")` and you don't have to make all of this again and again ;)

**Comment by zawalich** [comment]
I tried to do @j0bby solution, but unfortunately after removing the second / from URL there is still "Not Found" status. Any help?

**Comment by pablobarbera** [comment]
Thanks everyone for reporting this! It turned out to be a problem with the new version of httr. The latest version of instaR on GitHub (and soon on CRAN) should have fixed this problem.

**Comment by alex-danilin** [comment]
Hi.

I'm still having the same issue. Is it solved?

Tried to install package from GitHub and it didn't help.

**Comment by jgooly** [comment]
Experiencing the same issue as @alex-danilin. Using CRAN package version 0.2.2
After following @j0bby recommended solution, authentication worked.

**Comment by pablobarbera** [comment]
I'm about to release version 0.2.4 on CRAN. That should take care of the remaining authentication issues.

**Comment by eksande2** [comment]
Hi all,
I am still having this issue.  I am using the most up to date version of R and instaR.  I tried adding the extra / in the Sandbox settings, but that didn't make a difference.  Anything else I can try?  Thanks.

**Comment by alienalex6** [comment]
I'm having the exact same problem. Did anyone find a solution for this? Would really appreciate any help.
