### ISSUE TITLE
auth problem related to httr

### ISSUE THREAD

**Issue by digitaliteter** [pablobarbera/instaR#8]
First, thx for all your work Pablo.

When i try to auth i get the following error message. It seems like it is the same problem as with Rfacebook and latest httr ( http://stackoverflow.com/questions/31362523/rfacebook-authentication-error ).  

> my_oauth <- instaOAuth(app_id="XXXX", app_secret="XXXXX")
> Copy and paste into 'OAuth redirect_uri' on Instagram App Settings: http://localhost:1410 
> When done, press any key to continue...
> Error: Deprecated: supply token object to config directly

**Comment by pablobarbera** [comment]
Thanks for reporting it!
